cb-lcars-label-card:
  cblcars_card_type: cb-lcars-label-picard
  show_label: true
  variables:
    label: "LCARS Label"
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
cb-lcars-button-card:
  cblcars_card_type: cb-lcars-button-picard
  show_label: true
  variables:
    label: "LCARS Button"
  tap_action:
    action: toggle
  double_tap_action:
    action: none
  hold_action:
    action: more-info
cb-lcars-elbow-card:
  cblcars_card_type: cb-lcars-header
  enable_resize_observer: true
  tap_action:
    action: none
  double_tap_action:
    action: none
  hold_action:
    action: none
cb-lcars-dpad-card:
  enable_resize_observer: true
cb-lcars-multimeter-card:
  enable_resize_observer: true
  variables:
    entity_match_header: false
    entity_match_slider: false
    entity_match_gauge: false
    entity_match_slider_start: false
    entity_match_slider_end: false
    _mode: gauge
    _vertical: false
    _slider_mode: brightness
    card:
      border:
        left:
          size: 120
        top:
          size: 10
    gauge:
      sub_meter:
        show_sub_meter: true
    slider_track:
      bar_thickness: 10
      gap: 5
      bar_border_radius: 0
  tap_action:
    action: toggle
  double_tap_action:
    action: none
  hold_action:
    action: none
  show_label: false

